import type { Metadata } from "next";
import "../globals.css";
import { Toaster } from 'sonner';

//header
import { Header } from "../../components/header";
 

export const metadata: Metadata = {
  title: "MindFree | Financial Control",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <>
    
    <Header/>
      <Toaster
        position="bottom-right"
        toastOptions={{
          style: {
            backgroundColor: "#f1f1f1",
            color: "#131313",
            borderColor: "#252525"
          }
        }}
      />
      {children}
    </>

  );
}
