import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from 'sonner';

//Context
// import { MainContext } from '../context/index';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

        <body>
          <Toaster
            position="bottom-right"
            toastOptions={{
              style: {
                backgroundColor: "#f1f1f1",
                color: "#131313",
                borderColor: "#252525"
              }
            }}
          />
          {children}
        </body>
        
    </html>
  );
}
